In [2]:
import pandas as pd

In [3]:
# Tomamos una muestra, el proceso en la nube usara el archivo completo
df = pd.read_json('../../Data/tip.json', lines= True, nrows=100000)

In [4]:
df

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
99995,bKvJxHeOAASeruYRlvgx5g,Zi-F-YvyVOK0k5QD7lrLOg,Really overpriced and not very good. Great ser...,2017-04-13 03:35:52,0
99996,7cPYV4VCuO5IU4hMxzA3YA,iMTjejk6apJKzCukZnDw5A,Prepare to wait 15-30 minutes. This place is b...,2013-09-29 16:42:16,0
99997,fCvMnJU1Z-XhAjKg99wK3Q,Xwp9dHOS975h0EWmlEC2tw,BEST ENTRANCE:\nEnter through the Rite Aid Ent...,2017-07-17 07:53:37,0
99998,fRTGhUovTkqmDH8mxigP3Q,1fK1voue0RXNMXVBagvafA,My new discovery: they're dog-friendly! ... An...,2013-07-01 23:18:32,0
99999,QaCbRxUMAcTJl5YwA6inDA,F2C5ENuY8CXfgoW-gAMdDA,They opened early for us!,2012-09-01 20:02:17,0

In [5]:
# En la nube, este dataframe es extraido desde Big Query
df2 = pd.read_pickle('../../Data/business.pkl')

In [6]:
# Transformamos los datos parcialmente. En cloud los datos se usaran ya transformados
df2 = df2.loc[:, ~df2.columns.duplicated()]
df2 = df2[df2['city']=='Philadelphia']

In [7]:
# Queremos cargar solo las reviews a negocioes que estan en nuestro otro dataset
df =df[(df['business_id'].isin(df2['business_id']))]

In [8]:
df

,user_id,business_id,text,date,compliment_count
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
20,FQ-zmWPEG_pjSQx6pt3Efw,3ZynJ94VpIdDlaArmEp2Rg,"Yes, I'm eating here again. Breakfast!",2012-10-12 15:16:13,0
34,YnlCpuaBa3qWBp4te8pGmA,XIKYdKWq72zUYsq8NBxcCQ,The honey glazed salmon is amazing!,2018-01-14 15:00:01,0
48,Rr4cLb6Go91FT134o6RsKg,eMiN8nm70jjKg8izikVWDA,Mmm Yummy Crab Fries!,2011-10-16 23:43:10,0
53,fJhr0G2JBNkfqpbIwkEQHg,eJ77e9lGxY3ArzaoDbHhYw,"Good specials, nice menu",2013-02-16 21:34:37,0
...,...,...,...,...,...
99971,uRLCq4XPj_kcO8RSDO3jEg,REiAM73RkOxFqCVlEFiRWA,You. Gonna eat your tatter tots?,2016-02-18 02:57:40,0
99976,OG1plHx9jfsrojJ7qrN5TA,b6kCTSH1kHtfcHxUTm2odA,$15 Card Minimum,2017-01-19 21:28:32,0
99980,DX2EB2vxOG9lDrpe9uxrIA,vqzNQflkHpPchC_SVq8gTQ,Stone foot message Yes!,2011-02-26 21:17:40,0
99987,T6TInNEhz-qm5tT_ZjQEoA,W06QBC9vkxA5CVBNVrOMRA,Here's a tip: get here!!!,2011-01-29 16:23:51,0
99989,yPdPATvZ95l366Pp8nVzLQ,Bawf-t1gcb4TAxS4NRSqhg,Shad Fest!,2012-04-28 18:11:47,0

In [9]:
df.dtypes

user_id                     object
business_id                 object
text                        object
date                datetime64[ns]
compliment_count             int64
dtype: object

In [ ]:
#Modificamos el tipo de cada dato para que este alineado con el schema de big query
df['user_id']=df['user_id'].astype('string')
df['business_id']=df['business_id'].astype('string')
df['text']=df['text'].astype('string')